item {
    id: 0
    name: 'cat'
}

item {
    id: 1
    name: 'dog'
}

item {
    id: 2
    name: 'bird'
}

item {
    id: 3
    name: 'hamster'
}

item {
    id: 4
    name: 'fish'
}

item {
    id: 5
    name: 'rabbit'
}

item {
    id: 6
    name: 'frog'
}

item {
    id: 7
    name: 'turtle'
}

item {
    id: 8
    name: 'cucumber'
}

item {
    id: 9
    name: 'carrot'
}

item {
    id: 10
    name: 'pumpkin'
}

item {
    id: 11
    name: 'broccoli'
}

item {
    id: 12
    name: 'lemon'
}

item {
    id: 13
    name: 'bell_pepper'
}

item {
    id: 14
    name: 'cabbage'
}

item {
    id: 15
    name: 'potato'
}

item {
    id: 16
    name: 'strawberry'
}

item {
    id: 17
    name: 'banana'
}

item {
    id: 18
    name: 'apple'
}

item {
    id: 19
    name: 'orange'
}

item {
    id: 20
    name: 'pear'
}

item {
    id: 21
    name: 'pineapple'
}

item {
    id: 22
    name: 'tomato'
}

item {
    id: 23
    name: 'grape'
}

item {
    id: 24
    name: 'watermelon'
}

item {
    id: 25
    name: 'pomegranate'
}