item {
    id: 1
    name: 'Cat'
}

item {
    id: 2
    name: 'Dog'
}

item {
    id: 3
    name: 'Bird'
}

item {
    id: 4
    name: 'Hamster'
}

item {
    id: 5
    name: 'Fish'
}

item {
    id: 6
    name: 'Rabbit'
}

item {
    id: 7
    name: 'Frog'
}

item {
    id: 8
    name: 'Turtle'
}

item {
    id: 9
    name: 'Cucumber'
}

item {
    id: 10
    name: 'Carrot'
}

item {
    id: 11
    name: 'Pumpkin'
}

item {
    id: 12
    name: 'Broccoli'
}

item {
    id: 13
    name: 'Lemon'
}

item {
    id: 14
    name: 'Bell_pepper'
}

item {
    id: 15
    name: 'Cabbage'
}

item {
    id: 16
    name: 'Potato'
}

item {
    id: 17
    name: 'Strawberry'
}

item {
    id: 18
    name: 'Banana'
}

item {
    id: 19
    name: 'Apple'
}

item {
    id: 20
    name: 'Orange'
}

item {
    id: 21
    name: 'Pear'
}

item {
    id: 22
    name: 'Pineapple'
}

item {
    id: 23
    name: 'Tomato'
}

item {
    id: 24
    name: 'Grape'
}

item {
    id: 25
    name: 'Watermelon'
}

item {
    id: 26
    name: 'Pomegranate'
}